language: rust
rust:
  - 1.20.0
  - nightly

sudo: required
dist: trusty

# Add clippy
before_script:
  #- |
  #  if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
  #      ( ( cargo install clippy && export CLIPPY=true ) || export CLIPPY=false );
  #  fi
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo test --no-default-features

# Upload docs
after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_RUST_VERSION" == "1.20.0" ]]; then
    cargo doc --no-deps &&
    echo "<meta http-equiv=refresh content=0;url=os_balloon/index.html>" > target/doc/index.html &&
    git clone https://github.com/davisp/ghp-import.git &&
    ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
    echo "Uploaded documentation"
    fi
