[package]
name = "actix-web"
version = "0.3.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web framework"
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://github.com/actix/actix-web"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server", "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config",
           "appveyor.yml", "examples/static"]
build = "build.rs"

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_web"
path = "src/lib.rs"

[features]
default = []

# tls
tls = ["native-tls", "tokio-tls"]

# openssl
alpn = ["openssl", "openssl/v102", "openssl/v110", "tokio-openssl"]

[dependencies]
log = "0.4"
failure = "0.1"
failure_derive = "0.1"
h2 = "0.1"
http = "^0.1.2"
httparse = "1.2"
http-range = "0.1"
time = "0.1"
mime = "0.3"
mime_guess = "1.8"
regex = "0.2"
sha1 = "0.4"
url = "1.6"
libc = "0.2"
serde = "1.0"
serde_json = "1.0"
brotli2 = "^0.3.2"
percent-encoding = "1.0"
smallvec = "0.6"
bitflags = "1.0"
num_cpus = "1.0"
flate2 = "1.0"

# ring nightly compilation bug
# cookie = { version="0.10", features=["percent-encode", "secure"] }
cookie = { git="https://github.com/alexcrichton/cookie-rs.git", features=["percent-encode", "secure"] }

# io
mio = "0.6"
net2 = "0.2"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"

# native-tls
native-tls = { version="0.1", optional = true }
tokio-tls = { version="0.1", optional = true }

# openssl
tokio-openssl = { version="0.1", optional = true }

[dependencies.actix]
version = "^0.4.2"

[dependencies.openssl]
version = "0.9"
optional = true

[dev-dependencies]
env_logger = "0.4"
reqwest = "0.8"
skeptic = "0.13"
serde_derive = "1.0"

[build-dependencies]
skeptic = "0.13"
version_check = "0.1"

[profile.release]
lto = true
opt-level = 3
# debug = true

[workspace]
members = [
  "./",
  "examples/basics",
  "examples/diesel",
  "examples/json",
  "examples/hello-world",
  "examples/multipart",
  "examples/state",
  "examples/template_tera",
  "examples/tls",
  "examples/websocket",
  "examples/websocket-chat",
]
