[package]
name = "actix-web"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web framework"
readme = "README.md"
keywords = ["actor", "http", "web"]
homepage = "https://github.com/fafhrd91/actix-web"
repository = "https://github.com/fafhrd91/actix-web.git"
categories = ["network-programming", "asynchronous"]
license = "Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]

[badges]
travis-ci = { repository = "fafhrd91/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web" }
codecov = { repository = "fafhrd91/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_web"
path = "src/lib.rs"

[features]
default = []

# Enable nightly features
nightly = []

[dependencies]
log = "0.3"
time = "0.1"
http = "0.1"
httparse = "0.1"
http-range = "0.1"
mime = "0.3"
mime_guess = "1.8"
cookie = { version="0.10", features=["percent-encode"] }
regex = "0.2"
slab = "0.4"
sha1 = "0.2"
url = "1.5"

# tokio
bytes = "0.4"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"

[dependencies.actix]
#path = "../actix"
git = "https://github.com/fafhrd91/actix.git"
#version = "0.2"
default-features = false
features = []

[dev-dependencies]
env_logger = "*"

[profile.release]
lto = true
opt-level = 3
debug = true
