[package]
name = "actix-http"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix http"
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://actix.rs/api/actix-web/stable/actix_web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[package.metadata.docs.rs]
features = ["session"]

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_http"
path = "src/lib.rs"

[features]
default = ["session"]

# sessions feature, session require "ring" crate and c compiler
session = ["cookie/secure"]

# openssl
ssl = ["openssl", "actix-connector/ssl"]

[dependencies]
actix-service = "0.1.6"
actix-codec = "0.1.0"
# actix-connector = "0.1.0"
# actix-utils = "0.1.0"
actix-connector = { git = "https://github.com/actix/actix-net.git" }
actix-utils = { git = "https://github.com/actix/actix-net.git" }

base64 = "0.10"
backtrace = "0.3"
bitflags = "1.0"
bytes = "0.4"
byteorder = "1.2"
cookie = { version="0.11", features=["percent-encode"] }
derive_more = "0.13"
encoding = "0.2"
futures = "0.1"
hashbrown = "0.1.8"
h2 = "0.1.16"
http = "0.1.8"
httparse = "1.3"
indexmap = "1.0"
log = "0.4"
mime = "0.3"
percent-encoding = "1.0"
rand = "0.6"
serde = "1.0"
serde_json = "1.0"
sha1 = "0.6"
slab = "0.4"
serde_urlencoded = "0.5.3"
time = "0.1"
tokio-timer = "0.2"
tokio-current-thread = "0.1"
trust-dns-resolver = { version="0.11.0-alpha.1", default-features = false }

# openssl
openssl = { version="0.10", optional = true }

[dev-dependencies]
actix-rt = "0.1.0"
actix-web = "0.7"
actix-server = "0.1"
actix-http-test = { path="test-server" }
env_logger = "0.6"
serde_derive = "1.0"
