[package]
name = "actix-web"
version = "1.0.0-alpha.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web is a simple, pragmatic and extremely fast web framework for Rust."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_web"
path = "src/lib.rs"

[workspace]
members = [
  ".",
  "staticfiles",
]

[features]
default = ["brotli", "flate2-c"]

# brotli encoding, requires c compiler
brotli = ["brotli2"]

# miniz-sys backend for flate2 crate
flate2-c = ["flate2/miniz-sys"]

# rust backend for flate2 crate
flate2-rust = ["flate2/rust_backend"]

[dependencies]
actix-codec = "0.1.0"
actix-service = "0.3.0"
actix-utils = "0.3.0"
actix-rt = "0.1.0"

actix-http = { git = "https://github.com/actix/actix-http.git" }
actix-router = { git = "https://github.com/actix/actix-net.git" }

bytes = "0.4"
derive_more = "0.14"
encoding = "0.2"
futures = "0.1"
log = "0.4"
lazy_static = "1.2"
mime = "0.3"
num_cpus = "1.10"
parking_lot = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "^0.5.3"
threadpool = "1.7"

# compression
brotli2 = { version="^0.3.2", optional = true }
flate2 = { version="^1.0.2", optional = true, default-features = false }

[dev-dependencies]
actix-server = { version="0.3.0", features=["ssl"] }
actix-http = { git = "https://github.com/actix/actix-http.git", features=["ssl"] }
actix-http-test = { git = "https://github.com/actix/actix-http.git", features=["ssl"] }
rand = "0.6"
env_logger = "0.6"
serde_derive = "1.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
