[package]
name = "actix-web"
version = "0.4.5"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web is a small, pragmatic, extremely fast, web framework for Rust."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://github.com/actix/actix-web"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::http-client",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config",
           "appveyor.yml", "/examples/**"]
build = "build.rs"

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_web"
path = "src/lib.rs"

[features]
default = ["session"]

# tls
tls = ["native-tls", "tokio-tls"]

# openssl
alpn = ["openssl", "openssl/v102", "openssl/v110", "tokio-openssl"]

# sessions
session = ["cookie/secure"]

[dependencies]
actix = "^0.5.2"

base64 = "0.9"
bitflags = "1.0"
brotli2 = "^0.3.2"
failure = "0.1.1"
flate2 = "1.0"
h2 = "0.1"
http = "^0.1.5"
httparse = "1.2"
http-range = "0.1"
libc = "0.2"
log = "0.4"
mime = "0.3"
mime_guess = "2.0.0-alpha"
num_cpus = "1.0"
percent-encoding = "1.0"
rand = "0.4"
regex = "0.2"
serde = "1.0"
serde_json = "1.0"
sha1 = "0.6"
smallvec = "0.6"
time = "0.1"
encoding = "0.2"
language-tags = "0.2"
url = { version="1.7", features=["query_encoding"] }
cookie = { version="0.10", features=["percent-encode"] }

# io
mio = "^0.6.13"
net2 = "0.2"
bytes = "0.4"
byteorder = "1"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
trust-dns-resolver = "0.8"

# native-tls
native-tls = { version="0.1", optional = true }
tokio-tls = { version="0.1", optional = true }

# openssl
openssl = { version="0.10", optional = true }
tokio-openssl = { version="0.2", optional = true }

[dev-dependencies]
env_logger = "0.5"
skeptic = "0.13"
serde_derive = "1.0"

[build-dependencies]
skeptic = "0.13"
version_check = "0.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[workspace]
members = [
  "./",
  "examples/basics",
  "examples/juniper",
  "examples/diesel",
  "examples/r2d2",
  "examples/json",
  "examples/hello-world",
  "examples/http-proxy",
  "examples/multipart",
  "examples/state",
  "examples/redis-session",
  "examples/template_tera",
  "examples/tls",
  "examples/websocket",
  "examples/websocket-chat",
  "examples/web-cors/backend",
  "examples/unix-socket",
  "tools/wsload/",
]
