[package]
name = "actix-http"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix http"
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-http.git"
documentation = "https://actix.rs/api/actix-http/stable/actix_http/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[package.metadata.docs.rs]
features = ["session"]

[badges]
travis-ci = { repository = "actix/actix-http", branch = "master" }
appveyor = { repository = "fafhrd91/actix-http-b1qsn" }
codecov = { repository = "actix/actix-http", branch = "master", service = "github" }

[lib]
name = "actix_http"
path = "src/lib.rs"

[features]
default = ["fail"]

# openssl
ssl = ["openssl", "actix-connect/ssl"]

# failure integration. it is on by default, it will be off in future versions
# actix itself does not use failure anymore
fail = ["failure"]

[dependencies]
actix-service = "0.3.4"
actix-codec = "0.1.1"
actix-connect = { git = "https://github.com/actix/actix-net.git" }
actix-utils = "0.3.4"
actix-server-config = "0.1.0"

base64 = "0.10"
backtrace = "0.3"
bitflags = "1.0"
bytes = "0.4"
byteorder = "1.2"
cookie = { version="0.11", features=["percent-encode"] }
derive_more = "0.14"
encoding = "0.2"
futures = "0.1"
hashbrown = "0.1.8"
h2 = "0.1.16"
http = "0.1.8"
httparse = "1.3"
indexmap = "1.0"
lazy_static = "1.0"
language-tags = "0.2"
log = "0.4"
mime = "0.3"
percent-encoding = "1.0"
rand = "0.6"
regex = "1.0"
serde = "1.0"
serde_json = "1.0"
sha1 = "0.6"
slab = "0.4"
serde_urlencoded = "0.5.3"
time = "0.1"
tokio-tcp = "0.1.3"
tokio-timer = "0.2"
tokio-current-thread = "0.1"
trust-dns-resolver = { version="0.11.0-alpha.2", default-features = false }

# openssl
openssl = { version="0.10", optional = true }

# failure is optional
failure = { version = "0.1.5", optional = true }

[dev-dependencies]
actix-rt = "0.2.0"
actix-server = { version = "0.4.0", features=["ssl"] }
actix-connector = { version = "0.3.0", features=["ssl"] }
actix-http-test = { path="test-server", features=["ssl"] }

env_logger = "0.6"
serde_derive = "1.0"
openssl = { version="0.10" }
tokio-tcp = "0.1"