[package]
name = "actix-http"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix http support"
readme = "README.md"
keywords = ["actor", "http"]
homepage = "https://github.com/fafhrd91/actix-http"
repository = "https://github.com/fafhrd91/actix-http.git"
documentation = "https://fafhrd91.github.io/actix-http/actix-http/"
categories = ["network-programming", "asynchronous"]
license = "Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
build = "build.rs"

[lib]
name = "actix_http"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
time = "0.1"
http = "0.1"
httparse = "*"
hyper = "0.11"
route-recognizer = "0.1"

# tokio
bytes = "0.4"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"

# other
log = "0.3"
env_logger = "*"

#actix = { git="https://github.com/fafhrd91/actix.git" }

[dependencies.actix]
#path = "../actix"
git = "https://github.com/fafhrd91/actix.git"
features = ["signal"]

[dev-dependencies]
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"

[profile.release]
lto = true
opt-level = 3
debug = true
