[package]
name = "actix-http"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix http"
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://actix.rs/api/actix-web/stable/actix_web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::http-client",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]

[package.metadata.docs.rs]
features = ["tls", "alpn", "rust-tls", "session", "brotli", "flate2-c"]

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_http"
path = "src/lib.rs"

[features]
default = ["session", "cell"]

# native-tls
tls = ["native-tls", "tokio-tls", "actix-net/tls"]

# openssl
ssl = ["openssl", "tokio-openssl", "actix-net/ssl"]

# rustls
rust-tls = ["rustls", "tokio-rustls", "webpki", "webpki-roots", "actix-net/rust-tls"]

# unix sockets
uds = ["tokio-uds"]

# sessions feature, session require "ring" crate and c compiler
session = ["cookie/secure"]

cell = ["actix-net/cell"]

[dependencies]
actix = "0.7.0"
actix-net = { git="https://github.com/actix/actix-net.git" }
#actix-net = { path = "../actix-net" }

base64 = "0.9"
bitflags = "1.0"
http = "^0.1.8"
httparse = "1.3"
log = "0.4"
mime = "0.3"
rand = "0.5"
serde = "1.0"
serde_json = "1.0"
sha1 = "0.6"
time = "0.1"
encoding = "0.2"
lazy_static = "1.0"
serde_urlencoded = "^0.5.3"
cookie = { version="0.11", features=["percent-encode"] }

failure = "^0.1.2"

# io
net2 = "0.2"
bytes = "0.4"
byteorder = "1.2"
futures = "0.1"
tokio-codec = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-tcp = "0.1"
tokio-timer = "0.2"
tokio-current-thread = "0.1"

# native-tls
native-tls = { version="0.2", optional = true }
tokio-tls = { version="0.2", optional = true }

# openssl
openssl = { version="0.10", optional = true }
tokio-openssl = { version="0.2", optional = true }

#rustls
rustls = { version = "0.14", optional = true }
tokio-rustls = { version = "0.8", optional = true }
webpki = { version = "0.18", optional = true }
webpki-roots = { version = "0.15", optional = true }

# unix sockets
tokio-uds = { version="0.2", optional = true }

[dev-dependencies]
actix-web = "0.7"
env_logger = "0.5"
serde_derive = "1.0"

[build-dependencies]
version_check = "0.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
