[package]
name = "actix-web"
version = "1.0.0-alpha.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web is a simple, pragmatic and extremely fast web framework for Rust."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_web"
path = "src/lib.rs"

[workspace]
members = [
  ".",
  "actix-files",
  "actix-session",
  "actix-web-codegen",
]

[package.metadata.docs.rs]
features = ["ssl", "tls", "rust-tls"] #, "session"]

[features]
default = ["brotli", "flate2-c"]

# brotli encoding, requires c compiler
brotli = ["brotli2"]

# miniz-sys backend for flate2 crate
flate2-c = ["flate2/miniz-sys"]

# rust backend for flate2 crate
flate2-rust = ["flate2/rust_backend"]

# sessions feature, session require "ring" crate and c compiler
# session = ["actix-session"]

# tls
tls = ["native-tls", "actix-server/ssl"]

# openssl
ssl = ["openssl", "actix-server/ssl"]

# rustls
# rust-tls = ["rustls", "actix-server/rustls"]

[dependencies]
actix-codec = "0.1.0"
#actix-service = "0.3.2"
#actix-utils = "0.3.1"
actix-rt = "0.2.0"
actix-web-codegen = { path="actix-web-codegen" }

actix-service = { git = "https://github.com/actix/actix-net.git" }
actix-utils = { git = "https://github.com/actix/actix-net.git" }

actix-http = { git = "https://github.com/actix/actix-http.git" }
actix-router = { git = "https://github.com/actix/actix-net.git" }
actix-server = { git = "https://github.com/actix/actix-net.git" }
#actix-router = { path="../actix-net/router" }

bytes = "0.4"
derive_more = "0.14"
encoding = "0.2"
futures = "0.1"
hashbrown = "0.1.8"
log = "0.4"
lazy_static = "1.2"
mime = "0.3"
net2 = "0.2.33"
num_cpus = "1.10"
parking_lot = "0.7"
regex = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "^0.5.3"
threadpool = "1.7"
time = "0.1"
url = { version="1.7", features=["query_encoding"] }

# middlewares
# actix-session = { path="session", optional = true }

# compression
brotli2 = { version="^0.3.2", optional = true }
flate2 = { version="^1.0.2", optional = true, default-features = false }

# ssl support
native-tls = { version="0.2", optional = true }
openssl = { version="0.10", optional = true }
# rustls = { version = "^0.15", optional = true }

[dev-dependencies]
actix-http = { git = "https://github.com/actix/actix-http.git", features=["ssl"] }
actix-http-test = { git = "https://github.com/actix/actix-http.git", features=["ssl"] }
rand = "0.6"
env_logger = "0.6"
serde_derive = "1.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[patch.crates-io]
actix-service = { git = "https://github.com/actix/actix-net.git" }
