[package]
name = "actix-http"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix http"
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://actix.rs/api/actix-web/stable/actix_web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[package.metadata.docs.rs]
features = ["session"]

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_http"
path = "src/lib.rs"

[features]
default = ["session"]

# sessions feature, session require "ring" crate and c compiler
session = ["cookie/secure"]

# openssl
ssl = ["openssl", "actix-connector/ssl"]

[dependencies]
actix-service = "0.1.1"
actix-codec = "0.1.0"
actix-connector = "0.1.0"
actix-rt = "0.1.0"
actix-server = "0.1.0"
actix-utils = "0.1.0"

# actix-codec = { path="../actix-net/actix-codec/" }
# actix-connector = { path="../actix-net/actix-connector/" }
# actix-rt = { path="../actix-net/actix-rt/" }
# actix-server = { path="../actix-net/actix-server/" }
# actix-utils = { path="../actix-net/actix-utils/" }

base64 = "0.9"
bitflags = "1.0"
bytes = "0.4"
byteorder = "1.2"
cookie = { version="0.11", features=["percent-encode"] }
encoding = "0.2"
failure = "0.1.3"
futures = "0.1"
http = "0.1.8"
httparse = "1.3"
indexmap = "1.0"
log = "0.4"
mime = "0.3"
net2 = "0.2"
percent-encoding = "1.0"
rand = "0.5"
serde = "1.0"
serde_json = "1.0"
sha1 = "0.6"
slab = "0.4"
serde_urlencoded = "0.5.3"
time = "0.1"
tokio-tcp = "0.1"
tokio-timer = "0.2"
trust-dns-proto = "0.5.0"
trust-dns-resolver = "0.10.0"
url = { version="1.7", features=["query_encoding"] }

# native-tls
native-tls = { version="0.2", optional = true }

# openssl
openssl = { version="0.10", optional = true }

# rustls
rustls = { version = "^0.14", optional = true }

[dev-dependencies]
actix-web = "0.7"
env_logger = "0.5"
serde_derive = "1.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
