[package]
name = "actix-web"
version = "1.0.0-alpha.2"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web is a simple, pragmatic and extremely fast web framework for Rust."
readme = "README.md"
keywords = ["actix", "http", "web", "framework", "async"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
edition = "2018"

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_web"
path = "src/lib.rs"

[workspace]
members = [
  ".",
  "awc",
  "actix-http",
  "actix-files",
  "actix-session",
  "actix-web-actors",
  "actix-web-codegen",
]

[package.metadata.docs.rs]
features = ["ssl", "tls", "brotli", "flate2-zlib", "secure-cookies", "client", "rust-tls"]

[features]
default = ["brotli", "flate2-zlib", "secure-cookies", "client"]

# http client
client = ["awc"]

# brotli encoding, requires c compiler
brotli = ["actix-http/brotli"]

# miniz-sys backend for flate2 crate
flate2-zlib = ["actix-http/flate2-zlib"]

# rust backend for flate2 crate
flate2-rust = ["actix-http/flate2-rust"]

# sessions feature, session require "ring" crate and c compiler
secure-cookies = ["actix-http/secure-cookies"]

# tls
tls = ["native-tls", "actix-server/ssl"]

# openssl
ssl = ["openssl", "actix-server/ssl", "awc/ssl"]

# rustls
rust-tls = ["rustls", "actix-server/rust-tls"]

[dependencies]
actix-codec = "0.1.1"
actix-service = "0.3.4"
actix-utils = "0.3.4"
actix-router = "0.1.0"
actix-rt = "0.2.2"
actix-web-codegen = "0.1.0-alpha.1"
actix-http = { version = "0.1.0-alpha.2", features=["fail"] }
actix-server = "0.4.1"
actix-server-config = "0.1.0"
actix-threadpool = "0.1.0"
awc = { version = "0.1.0-alpha.2", optional = true }

bytes = "0.4"
derive_more = "0.14"
encoding = "0.2"
futures = "0.1"
hashbrown = "0.1.8"
httparse = "1.3"
log = "0.4"
mime = "0.3"
net2 = "0.2.33"
parking_lot = "0.7"
regex = "1.0"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
serde_urlencoded = "^0.5.3"
time = "0.1"
url = { version="1.7", features=["query_encoding"] }

# ssl support
native-tls = { version="0.2", optional = true }
openssl = { version="0.10", optional = true }
rustls = { version = "^0.15", optional = true }

[dev-dependencies]
actix-http = { version = "0.1.0-alpha.2", features=["ssl", "brotli", "flate2-zlib"] }
actix-http-test = { version = "0.1.0-alpha.2", features=["ssl"] }
rand = "0.6"
env_logger = "0.6"
serde_derive = "1.0"
tokio-timer = "0.2.8"
brotli2 = "0.3.2"
flate2 = "1.0.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
