[package]
name = "state"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../.."

[dependencies]
futures = "0.1"
env_logger = "0.5"
actix = "0.5"
actix-web = { path = "../../" }
