[package]
name = "actix-web-actors"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix actors support for actix web framework."
readme = "README.md"
keywords = ["actix", "http", "web", "framework", "async"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web-actors/"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "actix_web_actors"
path = "src/lib.rs"

[dependencies]
actix = "0.9.0"
actix-web = "2.0.0-rc"
actix-http = "1.0.1"
actix-codec = "0.2.0"
bytes = "0.5.2"
futures = "0.3.1"
pin-project = "0.4.6"

[dev-dependencies]
actix-rt = "1.0.0"
env_logger = "0.6"
