[package]
name = "actix-web-actors"
version = "3.0.0-alpha.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix actors support for actix web framework."
readme = "README.md"
keywords = ["actix", "http", "web", "framework", "async"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web-actors/"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "actix_web_actors"
path = "src/lib.rs"

[dependencies]
actix = "0.10.0-alpha.2"
actix-web = "3.0.0-alpha.3"
actix-http = "2.0.0-alpha.4"
actix-codec = "0.2.0"
bytes = "0.5.2"
futures-channel = { version = "0.3.5", default-features = false }
futures-core = { version = "0.3.5", default-features = false }
pin-project = "0.4.6"

[dev-dependencies]
actix-rt = "1.0.0"
env_logger = "0.7"
futures-util = { version = "0.3.5", default-features = false }
