[package]
name = "multipart-example"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../.."

[[bin]]
name = "multipart"
path = "src/main.rs"

[dependencies]
env_logger = "*"
futures = "0.1"
actix = "0.4"
actix-web = { path="../../" }
