[package]
name = "r2d2-example"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../.."

[dependencies]
env_logger = "0.5"
actix = { git = "https://github.com/actix/actix.git/" }
actix-web = { path = "../../" }

futures = "0.1"
uuid = { version = "0.5", features = ["serde", "v4"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

r2d2 = "*"
r2d2_sqlite = "*"
rusqlite = "*"
