[package]
name = "template-tera"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../.."

[dependencies]
env_logger = "0.4"
actix = "0.4"
actix-web = { path = "../../" }
tera = "*"
