[package]
name = "juniper-example"
version = "0.1.0"
authors = ["pyros2097 <pyros2097@gmail.com>"]
workspace = "../.."

[dependencies]
env_logger = "0.5"
actix = "0.5"
actix-web = { path = "../../" }

futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

juniper = "0.9.2"
