name: Semver Labeler

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  semver-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          toolchain: stable

      - uses: JohnTitor/cargo-semver-checks@3b76737b550e48ad0bd5912e2757e80eee6294b0 # v0.2.1
        with:
          label-prefix: B-semver-
          label-strategy: skip-if-human
