name: Upload Documentation

on:
  push:
    branches: [master]

permissions: {}
jobs:
  build:
    permissions:
      contents: write  #  to push changes in repo (jamesives/github-pages-deploy-action)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@nightly

      - name: Build Docs
        run: cargo +nightly doc --no-deps --workspace --all-features
        env:
          RUSTDOCFLAGS: --cfg=docsrs

      - name: Tweak HTML
        run: echo '<meta http-equiv="refresh" content="0;url=actix_web/index.html">' > target/doc/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: target/doc
          single-commit: true
